##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.17.1] date: [Tue Jul 26 19:25:52 GMT+06:00 2022]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = $(notdir $(CURDIR))


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

export PATH := C:/ST/STM32CubeIDE_1.7.0/STM32CubeIDE/plugins/com.st.stm32cube.ide.mcu.externaltools.make.win32_2.0.100.202202231230/tools/bin:C:/ST/STM32CubeIDE_1.7.0/STM32CubeIDE/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.win32_1.0.0.202111181127/tools/bin:$(PATH)

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/main.c \
Core/Src/gd32f20x_it.c \
Core/Src/gd32f20x_usb_hw.c \
Core/Src/usbh_usr.c \
Core/Src/system_gd32f20x.c \
Lib/SysTick/systick.c \
Lib/fat_fs/src/ff_gen_drv.c \
Lib/fat_fs/src/ff.c \
Lib/fat_fs/src/ffsystem.c \
Lib/LCD/LCD_Init.c \
Lib/LCD/cp866-8x16.c \
Lib/LCD/lcd.c \
Lib/LCD/SSD1963.c \
Drivers/GD32F20x_standard_peripheral/Source/gd32f20x_exmc.c \
Drivers/GD32F20x_standard_peripheral/Source/gd32f20x_gpio.c \
Drivers/GD32F20x_standard_peripheral/Source/gd32f20x_misc.c \
Drivers/GD32F20x_standard_peripheral/Source/gd32f20x_rcu.c \
Drivers/GD32F20x_standard_peripheral/Source/gd32f20x_timer.c \
Drivers/GD32F20x_usbfs_library/driver/Source/drv_usbh_int.c \
Drivers/GD32F20x_usbfs_library/driver/Source/drv_usb_host.c \
Drivers/GD32F20x_usbfs_library/driver/Source/drv_usb_core.c \
Drivers/GD32F20x_usbfs_library/host/core/Source/usbh_core.c \
Drivers/GD32F20x_usbfs_library/host/core/Source/usbh_enum.c \
Drivers/GD32F20x_usbfs_library/host/core/Source/usbh_pipe.c \
Drivers/GD32F20x_usbfs_library/host/core/Source/usbh_transc.c \
Drivers/GD32F20x_usbfs_library/host/class/msc/Source/usbh_msc_bbb.c \
Drivers/GD32F20x_usbfs_library/host/class/msc/Source/usbh_msc_core.c \
Drivers/GD32F20x_usbfs_library/host/class/msc/Source/usbh_msc_fatfs.c \
Drivers/GD32F20x_usbfs_library/host/class/msc/Source/usbh_msc_scsi.c
#Все это не используется и нет необходимости собирать это
# Lib/fat_fs/src/ffunicode.c \
# Drivers/GD32F20x_standard_peripheral/Source/gd32f20x_adc.c \
# Drivers/GD32F20x_standard_peripheral/Source/gd32f20x_bkp.c \
# Drivers/GD32F20x_standard_peripheral/Source/gd32f20x_can.c \
# Drivers/GD32F20x_standard_peripheral/Source/gd32f20x_cau_aes.c \
# Drivers/GD32F20x_standard_peripheral/Source/gd32f20x_cau_des.c \
# Drivers/GD32F20x_standard_peripheral/Source/gd32f20x_cau_tdes.c \
# Drivers/GD32F20x_standard_peripheral/Source/gd32f20x_cau.c \
# Drivers/GD32F20x_standard_peripheral/Source/gd32f20x_crc.c \
# Drivers/GD32F20x_standard_peripheral/Source/gd32f20x_dac.c \
# Drivers/GD32F20x_standard_peripheral/Source/gd32f20x_dbg.c \
# Drivers/GD32F20x_standard_peripheral/Source/gd32f20x_dci.c \
# Drivers/GD32F20x_standard_peripheral/Source/gd32f20x_dma.c \
# Drivers/GD32F20x_standard_peripheral/Source/gd32f20x_exti.c \
# Drivers/GD32F20x_standard_peripheral/Source/gd32f20x_fmc.c \
# Drivers/GD32F20x_standard_peripheral/Source/gd32f20x_fwdgt.c \
# Drivers/GD32F20x_standard_peripheral/Source/gd32f20x_hau_sha_md5.c \
# Drivers/GD32F20x_standard_peripheral/Source/gd32f20x_hau.c \
# Drivers/GD32F20x_standard_peripheral/Source/gd32f20x_i2c.c \
# Drivers/GD32F20x_standard_peripheral/Source/gd32f20x_pmu.c \
# Drivers/GD32F20x_standard_peripheral/Source/gd32f20x_rtc.c \
# Drivers/GD32F20x_standard_peripheral/Source/gd32f20x_sdio.c \
# Drivers/GD32F20x_standard_peripheral/Source/gd32f20x_spi.c \
# Drivers/GD32F20x_standard_peripheral/Source/gd32f20x_tli.c \
# Drivers/GD32F20x_standard_peripheral/Source/gd32f20x_trng.c \
# Drivers/GD32F20x_standard_peripheral/Source/gd32f20x_usart.c \
# Drivers/GD32F20x_standard_peripheral/Source/gd32f20x_wwdgt.c \
#Drivers/GD32F20x_standard_peripheral/Source/gd32f20x_enet.c \

# ASM sources
ASM_SOURCES =  \
Core/startup_gd32f20x.s


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m3

# fpu
# NONE for Cortex-M0/M0+/M3

# float-abi


# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_STDPERIPH_DRIVER \
-DGD32F20X_CL \
-DUSE_USB_FS \
-DHXTAL_VALUE=8000000ULL \
-DAPP1_START=0x0800C000ULL

# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-ICore/Inc \
-ILib/SysTick \
-ILib/fat_fs/inc \
-ILib/LCD \
-IDrivers/GD32F20x_standard_peripheral/Include \
-IDrivers/GD32F20x_usbfs_library/ustd/common \
-IDrivers/GD32F20x_usbfs_library/ustd/class/msc \
-IDrivers/GD32F20x_usbfs_library/driver/Include \
-IDrivers/GD32F20x_usbfs_library/host/core/Include \
-IDrivers/GD32F20x_usbfs_library/host/class/msc/Include \
-IDrivers/CMSIS/Device/GD/Include \
-IDrivers/CMSIS/Include


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = GD32F205VCTx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***